// ─── ASPECT DATA ──────────────────────────────────────────────────────────

export const SEASON_POINTS = [
  { angle:0,   name:"Breaking",  fn:"Initiating",   astroLabel:"March Equinox",
    tree:"Birch", treeDesc:"a slender trunk marking first growth",
    fragment:"treats stillness as something worth ending, and steps first to end it",
    color:"#4FAE63", tagline:"I turn stillness into a decision.",
    def:"Breaking is the decisive conversion of stillness into direction. It doesn't wait for permission or perfect conditions — it acts because something has to move, and moving is the only honest response to stagnation.",
    traits:["Decisive","Catalytic","Direct","Unafraid of disruption","Comfortable being first"],
    shadow:["Moves before understanding has caught up","Fractures stable situations unnecessarily","Sets direction unilaterally rather than together","Mistakes speed for clarity"] },

  { angle:45,  name:"Sprouting", fn:"Exploring",    astroLabel:"Cross-Quarter (≈ May 5)",
    tree:"Hawthorn", treeDesc:"a thorned branch in early bloom",
    fragment:"tests many doors at once, trusting contact over planning",
    color:"#A9C23F", tagline:"I'd rather try it than talk about it.",
    def:"Sprouting is motion multiplied — the instinct to test many doors rather than commit to the first one that opens. It treats the early stage of anything as an invitation to sample widely, trusting that contact with the world teaches faster than planning ever could.",
    traits:["Curious","Adaptable","Quick to engage","Open to revision","Energized by possibility"],
    shadow:["Scatters attention across more paths than it can follow","Trades depth for novelty","Avoids completion through perpetual trialing","Mistakes restlessness for growth"] },

  { angle:90,  name:"Cresting",  fn:"Actualizing",  astroLabel:"June Solstice",
    tree:"Oak", treeDesc:"a canopy at its fullest reach",
    fragment:"shows up at full capacity, holding nothing back at its peak",
    color:"#E8A33D", tagline:"Full intensity or nothing.",
    def:"Cresting is capability made fully visible — the point where preparation stops being private and becomes performance. It doesn't hold back at its peak; it shows, fully and undeniably, what it's capable of, because half-measures feel like a betrayal of the moment.",
    traits:["Confident","Expressive","High-capacity","Magnetic under pressure","Decisive in execution"],
    shadow:["Ties identity to peak intensity","Burns out through sustained overextension","Resists low-energy or transitional states","Dominates through presence rather than invitation"] },

  { angle:135, name:"Reaping",   fn:"Consolidating",astroLabel:"Cross-Quarter (≈ Aug 7)",
    tree:"Chestnut", treeDesc:"a bur splitting to release its yield",
    fragment:"gathers what worked and locks it into something that lasts",
    color:"#C17F3E", tagline:"I finish what gets started.",
    def:"Reaping is the act of turning effort into something that stays — gathering what scattered action produced and locking it into a form that can be relied on. It isn't interested in starting something new until what's already been built is properly secured.",
    traits:["Practical","Results-oriented","Organized","Protective of what works","Decisive about closure"],
    shadow:["Fixates on results over process meaning","Grows detached from what produced outcomes","Over-optimizes past success patterns","Resists reopening completed systems"] },

  { angle:180, name:"Reckoning", fn:"Evaluating",   astroLabel:"September Equinox",
    tree:"Maple", treeDesc:"a paired seed in balanced flight",
    fragment:"stops to ask what something actually amounted to, fairly and honestly",
    color:"#7B8B9E", tagline:"I want the honest tally, not the story.",
    def:"Reckoning is the restoration of clarity through honest accounting — pausing to ask what something actually amounted to, stripped of the story told about it in the moment. It trusts a fair tally over a comfortable narrative.",
    traits:["Discerning","Honest","Reflective","Fair-minded","Unafraid of hard truths"],
    shadow:["Turns weighing into a habit that never stops","Audits experiences past the point of usefulness","Brings comparison into relationships","Treats rest as something that must be justified"] },

  { angle:225, name:"Veiling",   fn:"Withdrawing",  astroLabel:"Cross-Quarter (≈ Nov 7)",
    tree:"Yew", treeDesc:"layered boughs drawn low and close",
    fragment:"steps back from the surface to understand what's underneath it",
    color:"#6B5B7B", tagline:"I step back to see clearly.",
    def:"Veiling is a deliberate retreat from the surface in order to see more clearly underneath it — stepping back from immediate engagement not to disappear, but to understand something properly before responding to it.",
    traits:["Perceptive","Selective","Composed","Comfortable with ambiguity","Internally oriented"],
    shadow:["Withdrawal substitutes for direct engagement","Ambiguity used as deflection","Real feeling stays unreadable to those closest","Presence arrives later than the moment needed it"] },

  { angle:270, name:"Kindling",  fn:"Sustaining",   astroLabel:"December Solstice",
    tree:"Holly", treeDesc:"a spiked leaf holding berries through frost",
    fragment:"holds its own flame steady, even when nothing from outside is feeding it",
    color:"#A8432F", tagline:"Steady is its own kind of strength.",
    def:"Kindling is the quiet maintenance of an inner flame through a period that offers nothing from the outside to keep it lit. It doesn't need conditions to be favorable in order to hold steady; holding steady is the whole point.",
    traits:["Steady","Self-renewing","Patient","Quietly resilient","Low-drama under pressure"],
    shadow:["Patience curdles into passivity","Under-asserts needs or direction","Stagnation gets relabeled as endurance","Anything that tries to activate it from outside meets quiet resistance"] },

  { angle:315, name:"Rooting",   fn:"Stabilizing",  astroLabel:"Cross-Quarter (≈ Feb 4)",
    tree:"Pine", treeDesc:"a taproot holding through thin soil",
    fragment:"turns everything it's lived through into a foundation built to last",
    color:"#5B4632", tagline:"I build what's meant to last.",
    def:"Rooting is structure formed from everything that's already been lived through — the slow conversion of accumulated experience into a foundation solid enough to build the next thing on. It values what lasts over what's merely new.",
    traits:["Dependable","Grounding","Loyal","Consistent","Quietly load-bearing for others"],
    shadow:["Mistakes familiarity for safety","Anchors in known systems past the point of usefulness","Emotional inertia in relationships","Resistance to change disguised as stability"] },
];

export const SYNODIC_MONTH = 29.530588853;
export const LUNAR_PHASES = [
  { day:0,                  name:"Pilgrim", animal:"Hare",   phaseLabel:"New Moon",
    fragment:"understands by stepping fully into experience, not by studying it from a distance",
    color:"#6E7191", tagline:"I understand by being in it.",
    def:"The Pilgrim makes meaning by stepping fully into experience and letting understanding arrive afterward, not before. It trusts contact over theory, certain that the only way to actually know something is to have already been inside it.",
    traits:["Porous","Curious","Adaptable","Present","Unafraid of the unfamiliar"],
    shadow:["Identity diffuses under accumulated exposure","Loops stay open","Novelty mistaken for truth","Feeling absorbed faster than it is filtered"] },

  { day:SYNODIC_MONTH*.25, name:"Adept",   animal:"Beaver", phaseLabel:"First Quarter Moon",
    fragment:"turns potential into progress through sustained, structured effort",
    color:"#8FB6D9", tagline:"Progress is how I make sense of things.",
    def:"The Adept makes meaning by shaping raw potential into something functional, refining both self and surroundings through sustained, structured effort. Progress isn't a side effect here — it's the actual point.",
    traits:["Disciplined","Capable","Methodical","Improvement-oriented","Reliable under sustained effort"],
    shadow:["Self-worth quietly fused to output","Rest requires justification","Method calcifies into rigidity","Control substituted for trust in emergence"] },

  { day:SYNODIC_MONTH*.5,  name:"Beacon",  animal:"Stag",   phaseLabel:"Full Moon",
    fragment:"makes what's true on the inside fully, visibly real on the outside",
    color:"#F4EED9", tagline:"What's true in me should be visible.",
    def:"The Beacon makes meaning by making the inner self externally legible — turning what's true on the inside into something visible, declared, and lived in the open rather than kept private.",
    traits:["Expressive","Charismatic","Clear","Confident in visibility","Naturally draws attention"],
    shadow:["Visibility quietly turns into performance","Being seen substitutes for being real","Authenticity becomes dependent on an audience","Constant exposure stops feeling like a choice"] },

  { day:SYNODIC_MONTH*.75, name:"Mystic",  animal:"Raven",  phaseLabel:"Last Quarter Moon",
    fragment:"withdraws from the noise to find the pattern actually underneath it",
    color:"#5C4A73", tagline:"I find meaning in what's underneath.",
    def:"The Mystic makes meaning by withdrawing from the noise of surface reality to extract whatever deeper pattern is actually underneath it. Distillation, not accumulation, is how it arrives at anything true.",
    traits:["Insightful","Reflective","Pattern-sensitive","Comfortable in solitude","Drawn to underlying structure"],
    shadow:["Withdrawal tips past usefulness into full retreat","Over-interpretation replaces action","Insight functions as distance rather than connection","Meaning gets refined instead of lived"] },
];

// ─── COMBINED ARCHETYPES ──────────────────────────────────────────────────

export const COMBOS = {
  "Breaking|Pilgrim":  { nickname:"The First Step",             tagline:"I don't wait to understand — I go find out.",
    symbol:"a traveler's staff planted beside a splitting seed",
    profile:"This is decisiveness in service of discovery. Where Breaking alone might charge ahead with a fixed plan, paired with the Pilgrim's experience-first orientation it becomes fearless improvisation — starting things not to prove a point but to find out what's actually there. This type moves first and discovers why afterward, trusting that contact with the new will teach faster than deliberation ever could. The risk is permanent restlessness: each new beginning absorbs completely, and the throughline of their own life can be hard even for them to locate.",
    traits:["Bold","Curious","Spontaneous","Adaptable","Magnetic to new beginnings"],
    shadow:["Impulsive without follow-through","Identity scattered across too many fresh starts","Mistakes the thrill of beginning for actual progress","Struggles to commit once novelty fades"] },

  "Breaking|Adept":    { nickname:"The Founder",                tagline:"I don't just start things. I build them to last.",
    symbol:"a chisel striking the moment a seed splits",
    profile:"This pairing channels the instinct to start things into the discipline to actually build them. Breaking supplies the willingness to convert stillness into direction; the Adept supplies the structured follow-through that keeps that direction from dissolving. The result reads as founder energy — the person who not only sees that something needs to begin, but immediately starts laying the groundwork to make it last. They tend to move fast and build cleanly, uncomfortable with the gap between 'we should do this' and 'here's how we're doing it.'",
    traits:["Entrepreneurial","Disciplined","Fast-moving","Structurally minded","Relentless about follow-through"],
    shadow:["Over-identifies with output and momentum","Treats stillness as failure","Forces premature structure onto things that needed more time","Burns out from refusing to pause"] },

  "Breaking|Beacon":   { nickname:"The Igniter",                tagline:"Watch me — I'm already moving.",
    symbol:"a beacon flame rising from a splitting seed",
    profile:"Few combinations are as outwardly visible. Breaking's instinct to convert stillness into direction meets the Beacon's drive to make the inner self externally legible, producing someone who doesn't just start things quietly but announces them, rallies people, and leads from the front. Their decisiveness reads as charisma because it's delivered with full presence. The risk is that the performance of starting things becomes more important than the starting itself, and a quiet beginning — one nobody watches — can start to feel not worth doing at all.",
    traits:["Charismatic","Decisive","Visible","Rallying","Naturally positioned as a leader"],
    shadow:["Needs an audience to fully commit to a direction","Conflates being seen leading with being right","Struggles with quiet or unglamorous beginnings","Identity inflates around the role of 'starter'"] },

  "Breaking|Mystic":   { nickname:"The Quiet Catalyst",         tagline:"I act first and explain later, mostly to myself.",
    symbol:"a spiral unfurling from a splitting seed",
    profile:"The least expected pairing in the set: outward decisiveness fused to an inward, withdrawal-oriented way of making sense of things. Breaking still does what it always does — ends inertia, moves first — but the Mystic processes the meaning of that action privately, often well after the fact. This type starts things cleanly and then disappears to metabolize what they've done, which makes them genuinely hard to read. They tend to make sharper, more considered first moves than other Breaking pairings. The tension is real: the urge to act and the urge to withdraw can become a loop where they keep almost starting things, circling through analysis until the moment has passed.",
    traits:["Decisively private","Considered","Hard to read","Sharp instincts","Comfortable acting without applause"],
    shadow:["Overthinks after the fact to the point of self-doubt","Withdraws from a direction already set in motion","Isolates the meaning of actions from the people affected","Talks themselves out of momentum entirely"] },

  "Sprouting|Pilgrim": { nickname:"The Wanderer",               tagline:"Why pick one path when there are six?",
    symbol:"a traveler's staff resting among branching shoots",
    profile:"This is exploration squared — two aspects pointed in exactly the same direction. Sprouting's instinct to test multiple paths rapidly meets the Pilgrim's conviction that meaning only arrives through direct contact with experience, producing someone who treats the entire world as a place to be sampled rather than studied from a distance. They pick things up quickly, move between interests with real ease, and are often the most genuinely open-minded type in any room. The cost is depth: with nothing pulling them toward consolidation, they can accumulate enormous breadth without ever turning any of it into expertise or a finished thing.",
    traits:["Endlessly curious","Quick to adapt","Broad-minded","Easy with the unfamiliar","Energized by variety"],
    shadow:["Depth consistently sacrificed for breadth","Avoids finishing under the guise of staying open","Identity stays fluid to the point of feeling unanchored","Mistakes constant novelty for genuine growth"] },

  "Sprouting|Adept":   { nickname:"The Tinkerer",               tagline:"I try everything until something actually works.",
    symbol:"a chisel shaping one shoot from many branching paths",
    profile:"This combination puts a restless, multi-path exploratory instinct inside a structured, progress-oriented frame — someone who experiments with real discipline, trying many approaches but actually building something from each attempt. Where Sprouting alone might scatter, the Adept's need for tangible progress keeps pulling each experiment toward a usable result. This is the prototyper, the person who tries six different methods to find out which one actually works. The friction shows as productive impatience: each new experiment promises progress, making it tempting to abandon a working method the moment a more interesting one appears.",
    traits:["Experimental","Resourceful","Quick-iterating","Practically minded","Comfortable in early-stage uncertainty"],
    shadow:["Abandons working methods chasing more interesting ones","Conflates trying something new with actual progress","Scatters effort across too many simultaneous experiments","Struggles to recognize when something is already finished"] },

  "Sprouting|Beacon":  { nickname:"The Performer of Possibility",tagline:"Come watch me figure it out in real time.",
    symbol:"a beacon flame atop a many-branched shoot",
    profile:"This pairing takes an exploratory, multi-path instinct and gives it a stage. Sprouting wants to try many things; the Beacon wants whatever's true on the inside to be visibly, externally lived — together producing someone who explores out loud, in public, pulling an audience along for each new direction. The trying-out itself becomes a kind of performance, energetic and inviting. The risk is that the audience starts to shape the exploring: trying something becomes partly about how it reads to whoever's watching, and they can find themselves chasing whichever new direction gets the most visible response.",
    traits:["Expressive","Exploratory","Socially magnetic","Quick to share new interests","Good at making curiosity contagious"],
    shadow:["Exploration shaped by audience reaction rather than genuine interest","Struggles to try things privately","Scattered focus compounded by needing visible engagement","Authenticity gets blurred with what performs well"] },

  "Sprouting|Mystic":  { nickname:"The Inner Cartographer",     tagline:"I collect the world and map it quietly.",
    symbol:"a spiral threading through a branching shoot",
    profile:"An unusually rich pairing: an outwardly exploratory behavioral style fused to an inward, distillation-oriented way of making meaning. The Sprouting instinct keeps this type sampling widely, but the Mystic insists that none of it counts until it's been processed and synthesized internally. The result is someone who explores constantly but privately maps what they find, often arriving at genuinely original insight by combining inputs nobody else thought to put together. The friction is between the appetite for new input and the slower work of synthesizing it — they can keep gathering faster than they can process, left with a private archive of half-integrated experience.",
    traits:["Synthesizing","Quietly perceptive","Intellectually omnivorous","Original in connecting ideas","Comfortable holding ambiguity"],
    shadow:["Accumulates more experience than they can actually process","Retreats into private interpretation rather than sharing","Mistakes endless gathering for understanding","Isolates insight from the people who inspired it"] },

  "Cresting|Pilgrim":  { nickname:"The Live Wire",              tagline:"I'm at my best with no script and no net.",
    symbol:"a traveler's staff raised against a cresting wave",
    profile:"This pairing puts full, peak-capacity self-expression in service of pure, in-the-moment experience — someone who performs at their best specifically when they're fully inside something, not when they're planning for it. Cresting wants undeniable, visible execution; the Pilgrim trusts experience over preparation. Together they produce a type that thrives on live, high-stakes, in-the-moment situations where there's no time to overthink, only to be fully present. They do their best work improvising under real conditions. The cost is consistency: their peak is so tied to immersive, unplanned conditions that calmer, deliberate settings feel like a different instrument entirely.",
    traits:["Exhilarating under pressure","Instinctive","Fully present","Magnetic in the moment","Thrives without a script"],
    shadow:["Capability becomes dependent on high-stakes conditions","Struggles to perform steadily without adrenaline","Chases intensity to feel like themselves","Burns out from needing constant peak conditions"] },

  "Cresting|Adept":    { nickname:"The Master Craftsman",       tagline:"I built the system that lets me peak on command.",
    symbol:"a chisel held steady inside a cresting wave",
    profile:"Peak performance built on real, accumulated discipline rather than raw instinct — the most reliably high-output type in the set. Cresting wants full, visible execution at maximum capacity; the Adept supplies the structured effort and refinement that makes that capacity something they can return to on demand. This type doesn't just perform well — they've built the system that lets them perform well repeatedly, treating mastery itself as the long project and each peak moment as evidence the project is working. The danger is that the system becomes inseparable from their identity: rest reads as falling behind, anything short of peak output reads as failure.",
    traits:["Masterful","Dependable at the highest level","Disciplined","Refinement-obsessed","Consistently high-capacity"],
    shadow:["Self-worth fused entirely to peak output","Treats rest as failure","Refines endlessly past the point of usefulness","Struggles to value anything that can't be measured as progress"] },

  "Cresting|Beacon":   { nickname:"The Star",                   tagline:"If I'm not at full volume, was I even there?",
    symbol:"a beacon flame blazing atop a cresting wave",
    profile:"The most amplified, most outwardly visible pairing possible: full peak-capacity execution combined with the drive to make the inner self externally legible. Together they describe someone who doesn't just perform at their best — they perform their best publicly, treating visibility as part of what makes the performance complete. This type tends to be genuinely magnetic at full intensity, comfortable carrying a room, unusually good at converting raw capability into something people actually want to watch. The risk is steepest here: identity becomes almost entirely dependent on the audience's response, and the gap between performing and simply existing can start to feel uncomfortably wide.",
    traits:["Magnetic","Commanding","Performs naturally under attention","Undeniable at full intensity","Built for visibility"],
    shadow:["Identity dependent on being witnessed","Private achievement feels incomplete","Chronic pressure to maintain peak visibility","Conflates being watched with being valued"] },

  "Cresting|Mystic":   { nickname:"The Hidden Virtuoso",        tagline:"My best work has no audience but me.",
    symbol:"a spiral folding inward beneath a cresting wave",
    profile:"This pairing holds real tension at its center: Cresting wants full, undeniable, visible execution at peak capacity; the Mystic wants meaning to come from withdrawal and private synthesis. The type produced tends to be capable of extraordinary peak performance that almost nobody actually witnesses, doing their most complete work alone or in very small, trusted settings, then retreating to process what happened rather than seeking any response to it. They can be genuinely startling when they do perform publicly, precisely because the gap between private capability and visible output is so wide.",
    traits:["Privately masterful","Intense in small or trusted settings","Self-contained","Capable of startling output","Uninterested in performing for its own sake"],
    shadow:["Capability stays hidden out of habit rather than choice","Struggles to let peak work be witnessed","Retreats from recognition even when it's earned","Mistakes invisibility for humility"] },

  "Reaping|Pilgrim":   { nickname:"The Collector of Experience",tagline:"Every experience earns its place in the harvest.",
    symbol:"a traveler's staff laid across a bundled sheaf",
    profile:"This pairing channels a results-oriented, consolidating instinct toward something unusual: gathering and securing not material outcomes but lived experience itself. Reaping wants to lock in what worked; the Pilgrim generates meaning purely through immersive contact with the world, producing someone who treats their own accumulated experiences as the actual harvest — collecting stories and firsthand knowledge the way other types collect achievements. They're unusually good at extracting the lesson from an experience once it's over. The tension: the Pilgrim's appetite for the next new thing can pull against Reaping's instinct to stop and consolidate.",
    traits:["Reflective","Good at extracting meaning from chaos","Experience-rich","Practically wise","Consolidates lessons quickly"],
    shadow:["Struggles to fully process one experience before chasing the next","Romanticizes the past faster than learning from it","Accumulates stories without integrating them","Mistakes collecting experience for actually settling anywhere"] },

  "Reaping|Adept":     { nickname:"The Builder of Systems",     tagline:"I don't just finish things — I make them repeatable.",
    symbol:"a chisel resting on a finished, bundled sheaf",
    profile:"Consolidation doubled — two aspects both oriented toward turning effort into something durable and functional. Reaping wants to gather results and lock them into stable form; the Adept wants structured, sustained progress toward genuinely useful outcomes. Together they describe someone who doesn't just finish what they start — they build the systems that make finishing repeatable. This type is what organizations quietly depend on to take a working idea and make it scale. The risk is structural conservatism: once something works, they can become deeply resistant to revisiting it, treating any proposed change as a threat rather than an improvement.",
    traits:["Systematic","Dependable","Protective of working solutions","Methodical","Genuinely skilled at scaling effort"],
    shadow:["Resists revisiting anything that already works","Treats proposed change as threat","Over-optimizes past the point of diminishing returns","Loses sight of why the system mattered in the first place"] },

  "Reaping|Beacon":    { nickname:"The Public Achiever",        tagline:"If it's not seen, did it really land?",
    symbol:"a beacon flame set atop a bundled sheaf",
    profile:"This pairing takes the instinct to consolidate and secure results and gives it an audience. Reaping wants tangible, locked-in outcomes; the Beacon wants the inner self made externally legible — together describing a type whose sense of accomplishment is completed by recognition, not just by the achievement itself. They tend to be genuinely good at presenting finished work in a way that lands, translating quiet effort into visible, credit-worthy results. The strain shows when results go unrecognized: because validation is part of how the consolidation actually completes itself for them, an unseen accomplishment can feel oddly unfinished.",
    traits:["Accomplished","Good at presenting results","Recognition-savvy","Outcome-driven","Confidently visible about success"],
    shadow:["Accomplishment feels incomplete without external recognition","Can prioritize visible wins over quieter progress","Ties self-worth to public credit","Struggles to value work nobody else sees"] },

  "Reaping|Mystic":    { nickname:"The Quiet Archivist",        tagline:"I keep my own private record of what I've learned.",
    symbol:"a spiral bound into a sheaf of grain",
    profile:"This pairing turns consolidation inward, producing someone who gathers and secures not public outcomes but private understanding. Reaping wants to lock in what worked; the Mystic wants meaning distilled through withdrawal and reflection — together describing a type that processes their own history carefully and privately, building an internal archive of what's actually been learned. They tend to be unusually self-aware, able to draw precise conclusions from their own past, and slow to repeat a mistake once they've truly metabolized it. The risk is a closed loop: genuine growth can stay invisible even to people very close to them.",
    traits:["Self-aware","Careful","Privately wise","Slow to repeat mistakes","Deeply consolidated internally"],
    shadow:["Processes growth so privately it goes unwitnessed","Can become insular about hard-won insight","Mistakes private resolution for actually addressing something with others","Resists revisiting settled conclusions even when new information arrives"] },

  "Reckoning|Pilgrim": { nickname:"The Honest Wanderer",        tagline:"I'll try it — and I'll tell you the truth after.",
    symbol:"a traveler's staff balanced across even scales",
    profile:"This pairing combines a fair-minded, evaluative instinct with an experience-first way of making meaning — someone who explores widely but doesn't let themselves off the hook about what any of it actually amounted to. They try many things and are unusually willing to admit, out loud, when one of them didn't work. This combination is well-balanced compared to some others, since the evaluative instinct keeps the exploratory one somewhat honest. The tension that remains is pacing: they can reckon with one experience just long enough to draw a fair conclusion before the pull toward the next new thing takes over.",
    traits:["Candid","Fair-minded about experience","Self-correcting","Exploratory but accountable","Refreshingly direct"],
    shadow:["Draws honest conclusions but rarely lingers long enough to apply them","Becomes a serial re-evaluator rather than a builder","Restlessness undercuts the value of their own honesty","Judges new experiences too quickly against past ones"] },

  "Reckoning|Adept":   { nickname:"The Auditor",                tagline:"Good enough isn't good enough yet.",
    symbol:"a chisel weighed on one side of even scales",
    profile:"This pairing fuses an evaluative, accounting-oriented instinct with a structured, progress-driven way of making meaning — one of the more rigorous, quality-control-minded types in the set. Reckoning wants an honest tally of what actually worked; the Adept wants sustained, disciplined progress toward something genuinely functional. Together they describe someone who doesn't just build things — they relentlessly check whether what they built actually holds up. The risk is a perfectionism that never quite releases: the evaluating instinct keeps finding one more thing to improve, and the productivity instinct keeps trying to fix it.",
    traits:["Rigorous","Quality-focused","Methodical","Honest about flaws","Relentlessly improvement-minded"],
    shadow:["Perfectionism delays release of genuinely finished work","Self-criticism compounds with productivity pressure into chronic dissatisfaction","Struggles to accept 'good enough'","Can audit a system long past the point of diminishing returns"] },

  "Reckoning|Beacon":  { nickname:"The Public Critic",          tagline:"I'll say the thing everyone's already thinking.",
    symbol:"a beacon flame balanced on a pair of even scales",
    profile:"This pairing puts an evaluative, truth-telling instinct on a public stage — someone who doesn't just form honest assessments privately but says them out loud, in the open, often to the people the assessment is actually about. Reckoning wants clear-eyed accounting of what's real; the Beacon wants the inner self made externally legible. Together they describe a type known for direct, sometimes uncomfortably honest public feedback. They tend to be valued in settings that need clarity over comfort, and their visibility makes their honesty land with real weight. The cost is relational: not every honest assessment is welcome the moment it's delivered.",
    traits:["Outspoken","Clear-eyed","Trusted for honest feedback","Comfortable with public disagreement","Values clarity over comfort"],
    shadow:["Honesty without enough softening reads as harsh","Struggles to withhold an assessment even when it isn't wanted","Conflates being right with being kind","Public candor can damage trust faster than it builds credibility"] },

  "Reckoning|Mystic":  { nickname:"The Inner Judge",            tagline:"My harshest critic lives inside my own head.",
    symbol:"a spiral resting at the fulcrum of even scales",
    profile:"This pairing turns evaluation fully inward — an instinct for honest accounting combined with a meaning-making style built on withdrawal and private synthesis. Reckoning wants clarity about what actually happened; the Mystic wants that clarity distilled in solitude, away from outside noise. Together they describe a type that holds themselves to genuinely exacting internal standards, rarely voiced and rarely relaxed. Other people often experience them as quietly wise, without fully knowing how much internal accounting produced that wisdom. The risk is severity: self-judgment can compound in private until it becomes disproportionate to whatever actually happened.",
    traits:["Exacting","Privately insightful","Self-disciplined in reflection","Quietly wise","Rigorous about their own history"],
    shadow:["Private self-judgment compounds without outside perspective","Struggles to forgive themselves at the rate they extend understanding to others","Insight curdles into rumination","Rarely lets a reckoning actually conclude"] },

  "Veiling|Pilgrim":   { nickname:"The Roaming Observer",       tagline:"I go everywhere and reveal almost nothing.",
    symbol:"a traveler's staff glimpsed behind a half-drawn veil",
    profile:"This pairing combines a withdrawing, distance-seeking instinct with a meaning-making style built on full immersion in experience — producing someone who moves through the world a great deal but stays quietly unreadable while doing it. Veiling wants reduced exposure and interpretive distance; the Pilgrim wants direct contact with the unfamiliar. Together they describe a type that travels, samples, and engages widely, but always from a slight remove: present in a room without ever being fully legible inside it. Real closeness, when it happens, tends to arrive slowly and on this type's own private timeline.",
    traits:["Discreet","Widely experienced","Hard to fully read","Quietly perceptive","Comfortable being present without being known"],
    shadow:["Withdrawal disguised as openness reads as inconsistency","Struggles to let intimacy match the breadth of experience","Uses constant movement to avoid being pinned down emotionally","Can leave relationships feeling one-sided"] },

  "Veiling|Adept":     { nickname:"The Private Engineer",       tagline:"I'll show you when it's finished. Not before.",
    symbol:"a chisel at work behind a half-drawn veil",
    profile:"This pairing fuses a withdrawing, distance-seeking instinct with a structured, progress-oriented way of making meaning — someone who builds extensively but almost entirely out of view. Veiling wants reduced surface engagement in service of deeper understanding; the Adept wants sustained, disciplined progress. Together they describe a type that works steadily and seriously on things nobody else gets to see until they're finished, if shown at all. They tend to be unusually self-sufficient, capable of long, focused stretches of effort without needing outside input. The cost is collaboration — this type can build entire systems alone that would have benefited from outside perspective much earlier.",
    traits:["Self-sufficient","Quietly industrious","Focused","Private about process","Capable of sustained solo effort"],
    shadow:["Avoids outside input even when it would genuinely help","Shares finished work too late for useful feedback","Isolation can slow the progress it's meant to protect","Mistakes working alone for working well"] },

  "Veiling|Beacon":    { nickname:"The Selective Performer",    tagline:"I'm fully present — for the people who've earned it.",
    symbol:"a beacon flame dimmed behind a drawn veil",
    profile:"This pairing holds real tension: a withdrawing, distance-keeping instinct paired with a meaning-making style built entirely on visible, external self-expression. Veiling wants reduced exposure; the Beacon wants the inner self made fully legible to others. The result is someone highly selective about when and where they're fully on — capable of real charisma and presence, but only once they've decided a setting is actually safe enough to be witnessed in. When this type opens up, it's a deliberate choice. The friction shows as inconsistency from the outside: people who've seen the expressive side are caught off guard when this type disappears entirely afterward.",
    traits:["Selectively magnetic","Deliberate about visibility","Capable of real presence when chosen","Hard to predict","Protective of who sees the full version"],
    shadow:["Withholds presence even from people who've earned it","Perceived as inconsistent or guarded","Uses selectivity to avoid the vulnerability of consistent visibility","Struggles to be known gradually rather than all at once"] },

  "Veiling|Mystic":    { nickname:"The Recluse",                tagline:"Alone is where I actually become myself.",
    symbol:"a spiral folding inward behind a drawn veil",
    profile:"Withdrawal doubled — two aspects both oriented toward distance and internal processing, producing the most genuinely private type in the entire set. Veiling wants reduced surface engagement to protect deeper perception; the Mystic wants meaning distilled through solitude and reflection. Together they describe someone for whom retreat isn't a coping mechanism but close to a natural state — most fully themselves away from other people, not despite the absence of company but because of it. This type tends to produce genuinely original insight. The risk, doubled along with everything else, is real isolation: with no part of this combination pulling outward, they can drift further from connection than even they intended.",
    traits:["Deeply private","Original in thought","Self-restoring through solitude","Undistracted by outside opinion","Comfortable with extended distance from others"],
    shadow:["Isolation compounds without any internal counterweight pulling them back","Mistakes withdrawal for self-sufficiency","Insight stays unshared and therefore unchecked","Can drift from connection further than even they intended"] },

  "Kindling|Pilgrim":  { nickname:"The Patient Wanderer",       tagline:"Even the hard stretch is worth experiencing.",
    symbol:"a traveler's staff resting beside a cupped ember",
    profile:"This pairing combines an instinct for quiet, internal endurance with a meaning-making style built on direct contact with experience — someone who holds steady through difficulty by staying curious about it rather than by gritting their teeth through it. Kindling wants to maintain internal coherence with little outside support; the Pilgrim wants to make meaning by engaging fully with whatever's actually in front of them. Together they describe a type that gets through hard, sparse periods by treating them as one more thing worth experiencing rather than as a problem to be endured. This gives their resilience an unusually light touch.",
    traits:["Resilient with a light touch","Curious even under strain","Adaptable to difficulty","Low-drama in hard periods","Steady without rigidity"],
    shadow:["Reframes genuine hardship as mere experience rather than addressing it","Can mistake tolerance for actual wellbeing","Stays too long in situations that need to change","Under-communicates real difficulty because it's being quietly absorbed"] },

  "Kindling|Adept":    { nickname:"The Steady Builder",         tagline:"I'm still here, still building, long after it got quiet.",
    symbol:"a chisel set down beside a tended ember",
    profile:"This pairing fuses sustained internal endurance with a structured, progress-driven way of making meaning — one of the most reliably consistent types in the set. Kindling wants to hold internal coherence through periods of little external input; the Adept wants disciplined, sustained effort toward something functional. Together they describe a type that keeps building, slowly and steadily, through conditions that would stall other types entirely. This is the person still quietly making progress during the long, unglamorous middle of a project, when momentum has faded and nobody's watching. The cost is a chronic difficulty asking for support.",
    traits:["Consistent","Quietly persistent","Self-sufficient under strain","Reliable over the long term","Steady through unglamorous stretches"],
    shadow:["Resists asking for help even when clearly needed","Mistakes self-sufficiency for the only acceptable response to strain","Can sustain a losing effort longer than is actually useful","Internal endurance masks real exhaustion from others"] },

  "Kindling|Beacon":   { nickname:"The Reluctant Light",        tagline:"I wasn't trying to inspire anyone. I just kept going.",
    symbol:"a beacon flame kept low, cupped like an ember",
    profile:"This pairing holds interesting tension: an instinct toward quiet, low-visibility endurance paired with a meaning-making style built on full external self-expression. Kindling wants to sustain itself with minimal outside input; the Beacon wants the inner self made visibly legible to others. The type produced tends to keep going through hard periods with a steadiness that, almost despite itself, becomes genuinely inspiring to watch. They don't seek an audience for their endurance, but when people witness it, it lands with real weight. The friction is that the visibility instinct can start to shape the endurance itself — performing a calm they don't fully feel.",
    traits:["Quietly inspiring","Steady under visible pressure","Authentic-feeling resilience","Becomes a source of strength for others","Calm without trying to be"],
    shadow:["Can start performing calm they don't actually feel once it's being witnessed","Struggles to be visibly struggling","Takes on the emotional weight of being other people's source of stability","Authenticity erodes once endurance becomes a watched performance"] },

  "Kindling|Mystic":   { nickname:"The Inner Flame",            tagline:"Nobody sees what it takes to keep this lit.",
    symbol:"a spiral coiled gently around a cupped ember",
    profile:"Two deeply internal aspects together — quiet sustained endurance and a meaning-making style built on withdrawal and private synthesis — producing what might be the most purely internal type in the whole set. Kindling wants to maintain coherence through sparse external conditions; the Mystic wants meaning distilled in solitude, away from the noise of the surface. Together they describe someone whose real strength is almost entirely invisible from outside: a steady internal fire that burns regardless of whether anyone ever sees the light from it. The cost is total invisibility — even people very close to this type may never fully grasp how much they're holding.",
    traits:["Privately resilient","Deeply self-contained","Wise from solitary endurance","Undemonstrative about real strength","Steady without needing to show it"],
    shadow:["Invisibility of their struggle can leave them genuinely unsupported","Others may not realize help is needed until strain is severe","Privacy about hardship reads as emotional unavailability","Withholds even the steadiness that might reassure people who care about them"] },

  "Rooting|Pilgrim":   { nickname:"The Settled Explorer",       tagline:"I can wander anywhere because I know where home is.",
    symbol:"a traveler's staff planted into deep roots",
    profile:"This pairing combines a foundation-building, stabilizing instinct with a meaning-making style oriented toward constant new experience — a type that manages to keep exploring without ever feeling unmoored. Rooting wants durable structure built from accumulated experience; the Pilgrim wants ongoing, direct contact with the unfamiliar. Together they describe someone who treats a stable foundation as what actually makes wide exploration safe to do. They tend to be the friend who travels constantly but always seems to land on their feet — anchored enough in who they are that new experience adds to them instead of destabilizing them.",
    traits:["Grounded","Adventurous without being reckless","Integrates new experience well","Stable identity","Comfortable balancing change and continuity"],
    shadow:["Foundation is perpetually under renovation and never quite feels finished","Can accumulate experience faster than it gets integrated","Occasionally mistakes restlessness for healthy exploration","Struggles to fully settle even when settling would serve them"] },

  "Rooting|Adept":     { nickname:"The Master Builder",         tagline:"Build it once. Build it right.",
    symbol:"a chisel set into stone above deep roots",
    profile:"Stabilization doubled — two aspects both oriented toward durable, functional structure, producing what may be the single most foundationally solid type in the entire set. Rooting wants lasting structure formed from accumulated experience; the Adept wants sustained, disciplined progress toward something genuinely useful. Together they describe someone who builds things meant to outlast the moment they were built in — methodical, patient, deeply unwilling to cut corners on anything load-bearing. Their work tends to hold up under real pressure precisely because so little of it was rushed. The risk is rigidity: this combination can become so committed to durability that it resists adaptation even when the world underneath the structure has genuinely changed.",
    traits:["Foundationally solid","Methodical","Dependable infrastructure for others","Unwilling to cut corners","Built for the long term"],
    shadow:["Resists adaptation even when circumstances have genuinely changed","Defends existing structure past the point it still serves its purpose","Mistakes rigidity for reliability","Slow to recognize when something needs to be rebuilt rather than reinforced"] },

  "Rooting|Beacon":    { nickname:"The Visible Foundation",     tagline:"I'm the one people quietly build their plans around.",
    symbol:"a beacon flame rising from deep roots",
    profile:"This pairing puts a stabilizing, foundation-building instinct in full public view — someone whose steadiness isn't just real, it's openly, visibly part of how they show up. Rooting wants durable structure built from lived experience; the Beacon wants the inner self made externally legible. Together they describe a type that doesn't hide their reliability — they lead with it, becoming the openly dependable presence other people orient around. This type tends to be unusually good at making other people feel secure. The cost is the pressure of always needing to look like the steady one: moments of genuine instability can feel like they have to be hidden.",
    traits:["Openly dependable","Visibly steady","Reassuring presence","Consistent in how they're perceived","Naturally trusted with others' security"],
    shadow:["Hides genuine instability to protect their visible reliability","Struggles to be supported because everyone assumes they're the support","Identity gets fused to always appearing steady","Rarely lets others see the effort their stability actually requires"] },

  "Rooting|Mystic":    { nickname:"The Deep Foundation",        tagline:"My foundation runs deeper than I'll ever explain.",
    symbol:"a spiral coiled through a deep root system",
    profile:"This pairing fuses a stabilizing, foundation-building instinct with a meaning-making style built on withdrawal and private synthesis — a type whose steadiness is real but almost entirely unannounced. Rooting wants durable structure formed from lived experience; the Mystic wants meaning distilled through solitude, away from outside noise. Together they describe someone who builds a genuinely deep, well-considered foundation for their own life, but does it quietly, privately, with no particular interest in anyone witnessing the process. Their stability is the kind that doesn't need defending out loud, since it was never built to be seen. The risk: even people close to this type can struggle to understand what they actually stand on.",
    traits:["Deeply settled","Privately resolute","Slow and thorough in self-understanding","Unshakeable without needing to prove it","Quietly wise about their own foundations"],
    shadow:["Stability remains invisible to people who could benefit from understanding it","Rarely explains their own groundedness even when asked","Can come across as closed off rather than simply private","Others may misread quiet certainty as distance or disinterest"] },
};